### ISSUE TITLE
Create test database

### ISSUE THREAD

**Issue by matt-baker** [macenv/pgdecibel#2]
A test environment with the extension needs to be set up

**Comment by matt-baker** [comment]
@JayCeeJr and I will look at tomorrow. Plan is to install on QA db.

**Comment by JayCeeJr** [comment]
@Derek-Anderson This is installed in the QA database.

192.168.105.99:5432

**Comment by matt-baker** [comment]
Thanks @JayCeeJr

**Comment by Derek-Anderson** [comment]
Thanks! @JayCeeJr Do I have admin access to QA?
